CREATE DATABASE demo
	DEFAULT CHARACTER SET = 'utf8mb4';

CREATE TABLE demo.user (  
	id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	username VARCHAR(255),
	email VARCHAR(255),
	password VARCHAR(63)
);

DROP TABLE demo.`user`

DELETE TABLE demo.`user`
