CREATE DATABASE demo
	DEFAULT CHARACTER SET = 'utf8mb4';

CREATE TABLE demo.user (  
	id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id VARCHAR(255) NOT NULL,
	username VARCHAR(255),
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255),
	active BOOLEAN DEFAULT True,
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE demo.`user`
